# Config Settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  highlighter: rouge
highlight: true
baseurl: /joylio.github.io
exclude: ['README.md', 'CNAME', .'.gitignore', 'LICENSE']
lsi: false

# Build Settings
permalink: pretty

#Blog Settings
future: true